#!/usr/bin/env zsh

setopt err_exit

testargs ()
{
    CONFIG_ARGS="$1"
    shift
    DISTCHECK_ARGS="$1"
    shift

    if test -d hyperdex-0.1.dev
    then
        chmod -R a+w hyperdex-0.1.dev
    fi
    git clean -xfd
    autoreconf -i
    ./configure ${=CONFIG_ARGS}
    make
    make check
    make dist
    make distcheck DISTCHECK_CONFIGURE_FLAGS=$DISTCHECK_ARGS
}

for carg in "" "--enable-python-bindings" "--enable-java-bindings" "--enable-java-bindings --enable-ycsb" "--enable-java-bindings --enable-ycsb --enable-python-bindings"
do
    for darg in "" "--enable-python-bindings" "--enable-java-bindings" "--enable-java-bindings --enable-ycsb" "--enable-java-bindings --enable-ycsb --enable-python-bindings"
    do
        testargs "${carg}" "${darg}"
    done
done
