/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hyperdex_client_Regex */

#ifndef _Included_org_hyperdex_client_Regex
#define _Included_org_hyperdex_client_Regex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hyperdex_client_Regex
 * Method:    checksSize
 * Signature: ()J
 */
JNIEXPORT HYPERDEX_API jlong JNICALL Java_org_hyperdex_client_Regex_checksSize
  (JNIEnv *, jobject);

/*
 * Class:     org_hyperdex_client_Regex
 * Method:    convertChecks
 * Signature: (JJJ)J
 */
JNIEXPORT HYPERDEX_API jlong JNICALL Java_org_hyperdex_client_Regex_convertChecks
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
