/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hyperdex_client_Iterator */

#ifndef _Included_org_hyperdex_client_Iterator
#define _Included_org_hyperdex_client_Iterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hyperdex_client_Iterator
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT HYPERDEX_API void JNICALL Java_org_hyperdex_client_Iterator_create
  (JNIEnv *, jobject);

/*
 * Class:     org_hyperdex_client_Iterator
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT HYPERDEX_API void JNICALL Java_org_hyperdex_client_Iterator_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_hyperdex_client_Iterator
 * Method:    finished
 * Signature: ()Z
 */
JNIEXPORT HYPERDEX_API jboolean JNICALL Java_org_hyperdex_client_Iterator_finished
  (JNIEnv *, jobject);

/*
 * Class:     org_hyperdex_client_Iterator
 * Method:    callback
 * Signature: ()V
 */
JNIEXPORT HYPERDEX_API void JNICALL Java_org_hyperdex_client_Iterator_callback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
