/* Copyright (c) 2015, Cornell University
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of HyperDex nor the names of its contributors may be
 *       used to endorse or promote products derived from this software without
 *       specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* This file is generated by bindings/java.py */

package org.hyperdex.client;

import java.util.List;
import java.util.Map;
import java.util.HashMap;

public class Microtransaction
{
    protected Microtransaction(Client client, String space)
    {
        this._create(client, space);
    }
    
    private native void _create(Client client, String space);
    
    public native Integer get(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer get_partial(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer put(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_put(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_put(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_put_or_create(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_put(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer put_if_not_exist(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer del(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_del(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_del(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer atomic_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_atomic_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_atomic_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_atomic_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer atomic_sub(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_atomic_sub(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_atomic_sub(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_atomic_sub(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer atomic_mul(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_atomic_mul(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_atomic_mul(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_atomic_mul(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer atomic_div(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_atomic_div(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_atomic_div(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_atomic_div(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer atomic_mod(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_atomic_mod(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_atomic_mod(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer atomic_and(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_atomic_and(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_atomic_and(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_atomic_and(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer atomic_or(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_atomic_or(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_atomic_or(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_atomic_or(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer atomic_xor(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_atomic_xor(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_atomic_xor(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer atomic_min(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_atomic_min(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_atomic_min(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer atomic_max(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_atomic_max(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_atomic_max(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer string_prepend(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_string_prepend(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_string_prepend(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_string_prepend(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer string_append(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_string_append(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_string_append(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_string_append(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer list_lpush(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_list_lpush(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_list_lpush(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_list_lpush(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer list_rpush(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_list_rpush(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_list_rpush(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_list_rpush(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer set_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_set_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_set_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer set_remove(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_set_remove(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_set_remove(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer set_intersect(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_set_intersect(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_set_intersect(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer set_union(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_set_union(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_set_union(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer document_rename(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_document_rename(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_document_rename(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_document_rename(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer document_unset(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer uxact_document_unset(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_document_unset(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_document_unset(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_remove(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_remove(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_remove(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_atomic_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_atomic_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_atomic_add(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_atomic_sub(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_atomic_sub(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_atomic_sub(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_atomic_mul(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_atomic_mul(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_atomic_mul(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_atomic_div(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_atomic_div(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_atomic_div(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_atomic_mod(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_atomic_mod(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_atomic_mod(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_atomic_and(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_atomic_and(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_atomic_and(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_atomic_or(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_atomic_or(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_atomic_or(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_atomic_xor(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_atomic_xor(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_atomic_xor(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_string_prepend(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_string_prepend(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_string_prepend(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_string_append(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_string_append(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_string_append(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_atomic_min(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_atomic_min(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_atomic_min(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer map_atomic_max(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer cond_map_atomic_max(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer group_map_atomic_max(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer search(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer search_describe(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer sorted_search(Map<String,Object> attrs) throws HyperDexClientException;

    public native Integer count(Map<String,Object> attrs) throws HyperDexClientException;
}
