#!/bin/sh

SPACE="space search key int number attributes
    bit01, bit02, bit03, bit04, bit05, bit06, bit07, bit08,
    bit09, bit10, bit11, bit12, bit13, bit14, bit15, bit16,
    bit17, bit18, bit19, bit20, bit21, bit22, bit23, bit24,
    bit25, bit26, bit27, bit28, bit29, bit30, bit31, bit32
    create 1 partition"
echo Trial 1
python test/runner.py --space="${SPACE}" -- {PATH}/test/search-stress-test -h {HOST} -p {PORT} -k int

SPACE="space search key string number attributes
    bit01, bit02, bit03, bit04, bit05, bit06, bit07, bit08,
    bit09, bit10, bit11, bit12, bit13, bit14, bit15, bit16,
    bit17, bit18, bit19, bit20, bit21, bit22, bit23, bit24,
    bit25, bit26, bit27, bit28, bit29, bit30, bit31, bit32
    create 1 partition"
echo Trial 2
python test/runner.py --space="${SPACE}" -- {PATH}/test/search-stress-test -h {HOST} -p {PORT} -k string

SPACE="space search key string number attributes
    bit01, bit02, bit03, bit04, bit05, bit06, bit07, bit08,
    bit09, bit10, bit11, bit12, bit13, bit14, bit15, bit16,
    bit17, bit18, bit19, bit20, bit21, bit22, bit23, bit24,
    bit25, bit26, bit27, bit28, bit29, bit30, bit31, bit32
    primary_index
    bit01, bit02, bit03, bit04, bit05, bit06, bit07, bit08,
    bit09, bit10, bit11, bit12, bit13, bit14, bit15, bit16,
    bit17, bit18, bit19, bit20, bit21, bit22, bit23, bit24,
    bit25, bit26, bit27, bit28, bit29, bit30, bit31, bit32
    create 8 partitions"
echo Trial 3
python test/runner.py --space="${SPACE}" -- {PATH}/test/search-stress-test -h {HOST} -p {PORT} -k string

SPACE="space search key string number attributes
    bit01, bit02, bit03, bit04, bit05, bit06, bit07, bit08,
    bit09, bit10, bit11, bit12, bit13, bit14, bit15, bit16,
    bit17, bit18, bit19, bit20, bit21, bit22, bit23, bit24,
    bit25, bit26, bit27, bit28, bit29, bit30, bit31, bit32
    subspace bit01, bit02, bit03, bit04, bit05, bit06, bit07, bit08
    subspace bit09, bit10, bit11, bit12, bit13, bit14, bit15, bit16
    subspace bit17, bit18, bit19, bit20, bit21, bit22, bit23, bit24
    subspace bit25, bit26, bit27, bit28, bit29, bit30, bit31, bit32
    create 8 partitions"
echo Trial 4
python test/runner.py --space="${SPACE}" -- {PATH}/test/search-stress-test -h {HOST} -p {PORT} -k string || exit 1

SPACE="space search key string number attributes
    bit01, bit02, bit03, bit04, bit05, bit06, bit07, bit08,
    bit09, bit10, bit11, bit12, bit13, bit14, bit15, bit16,
    bit17, bit18, bit19, bit20, bit21, bit22, bit23, bit24,
    bit25, bit26, bit27, bit28, bit29, bit30, bit31, bit32
    subspace bit01, bit02, bit03, bit04, bit05, bit06, bit07, bit08
    secondary_index bit09, bit10, bit11, bit12, bit13, bit14, bit15, bit16
    subspace bit09, bit10, bit11, bit12, bit13, bit14, bit15, bit16
    secondary_index bit17, bit18, bit19, bit20, bit21, bit22, bit23, bit24
    subspace bit17, bit18, bit19, bit20, bit21, bit22, bit23, bit24
    secondary_index bit25, bit26, bit27, bit28, bit29, bit30, bit31, bit32
    subspace bit25, bit26, bit27, bit28, bit29, bit30, bit31, bit32
    secondary_index bit01, bit02, bit03, bit04, bit05, bit06, bit07, bit08
    create 8 partitions"
echo Trial 5
python test/runner.py --space="${SPACE}" -- {PATH}/test/search-stress-test -h {HOST} -p {PORT} -k string
